name: Run main.py every 4 hours

on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run main.py
        run: python main.py

      - name: Debug Check clustered.csv content
        run: cat datasets/clustered.csv

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add datasets/clustered.csv
          git commit -m "Update clustered.csv from GitHub Actions"
          git push

